[package]
name = "twitch_irc"
authors = ["JÃºlia Paschoalinoto <julia@juliapixel.com>"]
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
hashbrown = { version = "0.13" }
log = "0.4"
serde = { version = "1.0", features = ["derive"], optional = true }
tokio = { version = "1.27", features = ["sync", "rt"] }
tokio-tungstenite = { version = "0.18", features = ["native-tls"] }
rand = "0.8"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "benches"
harness = false

[features]
serde = ["dep:serde", "hashbrown/serde"]
